apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  namespace: dev
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-container
          image: IMAGE_URI_PLACEHOLDER  # 👈 this will be replaced dynamically
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_OPTS
              value: "-Xms256m -Xmx512m"
