name: Build and Push to ECR

on:
  push:
    branches:
      - master  # or any branch you prefer

env:
  AWS_REGION: us-east-1
  ECR_REGISTRY: 662792376110.dkr.ecr.us-east-1.amazonaws.com
  ECR_REPOSITORY: demo
  IMAGE_TAG: ${{ github.sha }}   # unique image tag per commit
  IMAGE_URI: 662792376110.dkr.ecr.us-east-1.amazonaws.com/demo:${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # ✅ Build the JAR first
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8

      - name: Build Java app with Gradle
        run: |
           ./gradlew clean build -x test
            ls -lat
            
      - name: List local Docker images
        run: docker images

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_URI .
          docker images


      - name: Tag Docker image
        run: |
          docker tag $ECR_REPOSITORY/demo:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_$TAG

      - name: Push to Amazon ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      #- name: Output image URI
        #run: echo "Image pushed to: ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
