name: Hello World Workflow

on:
  push:
    branches:
      - master  # Change this if your default branch is different

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, world!"
